#ifndef __FEATURES_BOOM_
#define __FEATURES_BOOM_

// REMEMEBR    - whether monsters remember last enemy
#define REMEMBER

// CHEATBOM    - controls if cheat codes introduced by BOOM are available
#define CHEATBOOM

// RECOIL      - controls if weapon recoil is available
#define RECOIL

// PHYSBOOM    - whether variable friction physics is supported
#define PHYSBOOM

// PUSHERS     - controls pushers code, states, etc.
#define PUSHERS

// V11V12LUMPS - inclusion of lumps missing from
// TODO: remove altogether in the future, as these are commercially 
//       licensed resources likely taken directly from IWAD -- LP 2024
#define V11V12LUMPS

#endif
