#ifndef __FEATURES_KRFN_
#define __FEATURES_KRFN_

// KRFNDFLT    - use defaults for options which are closer to vanilla
//               except some which are not (e.g. prefer BMP screenshots)
#define KRFNDFLT

// KRFNSLIM    - remove some of the less frequently used bits an pieces
#define KRFNSLIM

// AIRTELEPT   - whether to include compatibility with Final Doom
//               teleport bug, also adds comp_airteleport to toggle
#define AIRTELEPT

// USEVESA     - adds option to enable/disable search for VESA modes
#define USEVESA

#endif
